version: '3'
services:
  abs_capinode:
    user: "${LOCAL_UID:-1001}"
    image: kheaactua/capinode:1
    init: true
    environment:
      - SSH_AUTH_SOCK=/run/host/ssh-auth.sock
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SSH_AUTH_SOCK}:/run/host/ssh-auth.sock

      # Matt: Bash aliases and stuff.
      - ${HOME}/dotfiles/rclib.dot:${LOCAL_USERHOME:-/home/${LOCAL_USERNAME:-developer}}/dotfiles/rclib.dot:ro
      - ${HOME}/dotfiles/stow/bash/.bash_aliases:${LOCAL_USERHOME:-/home/${LOCAL_USERNAME:-developer}}/.bash_aliases:ro
    networks:
      - amf

    # Adding NET_ADMIN to allow a user to manually modify the network interface, i.e.:
    # ip link set down dev eth0
    privileged: false
    cap_add:
      - NET_ADMIN
